# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GayaniMadhushika-ios-cobsccomp182p-009' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GayaniMadhushika-ios-cobsccomp182p-009
	pod 'Firebase/Analytics'
	pod 'Firebase/Core'
	pod 'FirebaseAuth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Database'
	pod 'GoogleMaps', '~> 2.1.1'
	pod 'Firebase/Storage'
	pod 'FacebookCore'
	pod 'FacebookLogin'
	pod 'FacebookShare'


  target 'GayaniMadhushika-ios-cobsccomp182p-009Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GayaniMadhushika-ios-cobsccomp182p-009UITests' do
    # Pods for testing
  end

end
